# Generated by Django 4.2 on 2023-04-22 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_topic_room_host_message_room_topic'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['-updated', '-created']},
        ),
        migrations.RenameField(
            model_name='room',
            old_name='update',
            new_name='updated',
        ),
    ]
